apiVersion: apps/v1
kind: Deployment
metadata:
  name: springtrader
  labels:
    app: springtrader
    version: {{ .Values.version }}
spec:
  selector:
    matchLabels:
      app: springtrader
  template:
    metadata:
      labels:
        app: springtrader
        version: {{ .Values.version }}
    spec:
      initContainers:
      - name: wait-for-nanodbserver
        image: bitnami/kubectl:1.15
        args: ['wait','--for=condition=ready','pod/nanodbserver-0','--timeout=300s']
      - name: wait-for-schema
        image: {{ .Values.image }}
        command: ['sh','-c','./checkSqlfSchema']
        env:
        - name: GROOVY_HOME
          value: '/usr/bin'
        resources:
          requests:
            memory: "192Mi"
            cpu: "32m"
          limits:
            memory: "384Mi"
            cpu: "256m"
      containers:
      - name: springtrader
        image: {{ .Values.image }}
        resources:
          requests:
            memory: "1500Mi"
            cpu: "256m"
          limits:
            memory: "2000Mi"
            cpu: "1"
        env:
        - name: GROOVY_HOME
          value: '/usr/bin'
        livenessProbe:
          httpGet:
            path: /spring-nanotrader-services/api/marketSummary
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /spring-nanotrader-services/api/marketSummary
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 5
      - name: rabbitmq
        image: rabbitmq
        resources:
          requests:
            memory: "96Mi"
            cpu: "16m"
          limits:
            memory: "256Mi"
            cpu: "100m"
